# Generated by Django 3.2.23 on 2024-12-01 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('cnfpassword', models.CharField(max_length=100)),
                ('city1', models.CharField(max_length=100)),
                ('city2', models.CharField(max_length=100)),
                ('city3', models.CharField(max_length=100)),
                ('city4', models.CharField(max_length=100)),
                ('city5', models.CharField(max_length=100)),
            ],
        ),
    ]
