# Generated by Django 3.2.23 on 2024-12-01 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='cnfpassword',
        ),
    ]
